import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // The docs generator excludes samples from this tree; their URLs stay intact.
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  samplesSidebar: [
    {type: 'doc', id: 'samples/index', label: 'Overview'},
    'samples/calculator',
    'samples/planner',
    'samples/sales-desk',
    'samples/learning-hub',
    'samples/mail',
    'samples/runtime-coverage',
  ],
};

export default sidebars;
